---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  namespace: default
secrets:
- name: test-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  annotations:
    kubernetes.io/service-account.name: test
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  serviceAccountName: test
  containers:
  - image: zembutsu/docker-sample-nginx:latest
    name: hello-world
    ports:
    - containerPort: 80
